name: build

env:
  PETSC_VERSION: 3.17.0

on:
  push:
    branches:
      - next
  pull_request:
    branches:
      - next

jobs:
  build:
    name: ${{ matrix.os }}-vtk:${{ matrix.vtk }}-lua:${{ matrix.lua }}-shared:${{ matrix.shared }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-11]
        vtk: [ON, OFF]
        include:
          - vtk: ON
            lua: ON
            shared: OFF
          - vtk: OFF
            lua: OFF
            shared: ON
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Install dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update -qq
          sudo apt install \
            cmake \
            mpich \
            libblas-dev \
            liblapack-dev \
            lua5.4 liblua5.4-dev
      - name: Install dependencies
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install cmake automake lcov
          brew install mpich
          brew install lua
          brew install vtk
      - name: Install VTK
        if: matrix.vtk == 'ON' && startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt install libvtk9-dev
      - name: Update alternatives
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo update-alternatives --set mpi /usr/bin/mpicc.mpich
          sudo update-alternatives --set mpirun /usr/bin/mpirun.mpich
          sudo update-alternatives --set mpi-x86_64-linux-gnu /usr/include/x86_64-linux-gnu/mpich
      - name: Setup env
        run: |
          echo "CC=mpicc" >> $GITHUB_ENV
          echo "CXX=mpicxx" >> $GITHUB_ENV
          echo "FC=mpif90" >> $GITHUB_ENV
          echo "PETSC_ARCH=arch-chitech-c-opt" >> $GITHUB_ENV
      - name: Build PETSc
        run: |
          cd ${{ github.workspace }}
          wget -q https://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-${PETSC_VERSION}.tar.gz
          tar -xzf petsc-${PETSC_VERSION}.tar.gz
          cd petsc-${PETSC_VERSION}
          echo "::group::configure"
          ./configure \
            --prefix=${{ github.workspace }}/petsc \
            --shared-libraries \
            --with-debugging=no \
            --with-64-bit-indices=yes \
            --with-cxx-dialect=cxx14 \
            --with-pic=yes \
            --with-ssl=no \
            --download-hypre \
            --download-metis \
            --download-parmetis \
            --CC=$CC \
            --CXX=$CXX \
            --FC=$FC \
            PETSC_DIR=`pwd`
          echo "::endgroup::"
          echo "::group::make"
          make PETSC_DIR=`pwd` all
          make PETSC_DIR=`pwd` install
          echo "::endgroup::"
      - name: Setup PETSc env
        run: |
          echo "PETSC_ROOT=${{ github.workspace }}/petsc" >> $GITHUB_ENV
      - name: Setup VTK env
        if: matrix.vtk == 'ON'
        run: |
          echo "VTK_DIR=/usr" >> $GITHUB_ENV
      - name: Configure
        run: |
          cmake -S . -B ${{ github.workspace }}/build \
            -DCHITECH_WITH_VTK=${{ matrix.vtk }} \
            -DCHITECH_WITH_LUA=${{ matrix.lua }} \
            -DBUILD_SHARED_LIBS=${{ matrix.shared }}
      - name: Build
        run: make -C ${{ github.workspace }}/build
      - name: Run tests (diffusion)
        if: matrix.lua == 'ON'
        run: python3 ChiTest/Z_Run_all.py "tests_to_run=[range(1,13)]"
